#!/bin/sh

bspc monitor -d I II III IV
bspc config border_width         0
bspc config window_gap           7
bspc config split_ratio          0.50
bspc config focus_follows_pointer true
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true
bspc config single_monocle true
bspc config border_width         0

bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#3f3f3f"
#--experimental-backends
killall picom
setxkbmap -layout rs -variant latin &
picom &
xsetroot -cursor_name left_ptr &
feh --bg-fill ~/Pictures/Wallpapers/scenic2.jpg &

/home/darko/.config/polybar/launch.sh &
sxhkd &

